language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
install:
  - "cpanm -n EV IO::Socket::Socks IO::Socket::SSL Net::DNS::Native"
  - "cpanm -n --installdeps ."
sudo: false
